### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by NoahHahm** [hydro-sdk/hotel-booking-app#119]
flutter doctor
````
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.2.3 20D91 darwin-x64, locale ko-KR)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.58.2)
[✓] Connected device (4 available)
````

````
noah@Noahui-iMac hotel-booking-app % flutter run
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Upgrading contents.xcworkspacedata
Running pod install...                                             951ms
Running Xcode build...                                                  
 └─Compiling, linking and signing...                      2,259ms
Xcode build done.                                           17.2s
Syncing files to device iPhone 12 Pro Max...                       111ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

An Observatory debugger and profiler on iPhone 12 Pro Max is available at:
http://127.0.0.1:57812/24mLleIp-pA=/
flutter: Invalid argument(s): No host specified in URI https:///api/package/latest
flutter: #0      _HttpClient._openUrl (dart:_http/http_impl.dart:2636:9)
#1      _HttpClient.openUrl (dart:_http/http_impl.dart:2560:7)
#2      IOClient.send (package:http/src/io_client.dart:30:38)
#3      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:38)
#4      BaseClient.post (package:http/src/base_client.dart:32:7)
#5      post.<anonymous closure> (package:http/http.dart:69:16)
#6      _withClient (package:http/http.dart:164:20)
#7      post (package:http/http.dart:68:5)
#8      RegistryApi.getLatestPackage (package:hydro_sdk/registry/registryApi.dart:315:28)
#9      _RunComponentState._attemptToLoadComponentFromRegistry (package:hydro_sdk/runComponent/runComponent.dart:120:60)
<asynchronous suspension>
The Flutter DevTools debugger and profiler on iPhone 12 Pro Max is available at:
http://127.0.0.1:9100?uri=http%3A%2F%2F127.0.0.1%3A57812%2F24mLleIp-pA%3D%2F
Application finished.
````

I get the above error when building in my flutter environment.
````
  runApp(const RunComponent(
      project: "example-project",
      component: "hotel-booking",
      registryApi: RegistryApi(
        scheme: "https",
        host: "api.registry.hydro-sdk.io",
  ))); 
````
So I added the above code and the error was solved.
However, if it is built, normal rendering is not possible on the screen.

<img src="https://user-images.githubusercontent.com/6405162/127521896-df8e8b5f-ad0c-43a1-9fcf-7465cfed0740.png" width="30%" />

**Comment by NoahHahm** [comment]
the counter app was well exposed to the simulator.
Is there something I'm missing out on?

**Comment by chgibb** [comment]
Hi @NoahHahm, thanks for checking out Hydro-SDK! The main branch of this repository is slightly out of date with the current Hydro-SDK release. The main branch of this repository is on Hydro-SDK 0.0.1-nightly.285 at time of writing. The bug you fixed by adding a default `RegistryApi` object was fixed [in this commit](https://github.com/hydro-sdk/hydro-sdk/commit/b7857254ea7a62dd3a3dba188e86312a96010a38) which was released in Hydro-SDK 0.0.1-nightly.286 and 0.0.1-alpha.0.

I suspect the reason you're not seeing anything render is because you're not running `npx hydroc run` at the same time. When running in debug mode, `RunComponent` will look for `npx hydroc run` to be running. If it's not, it will look to run the component from the registry (`registry.hydro-sdk.io` by default). `example-project/hotel-booking` does not exist on the registry and therefore nothing is rendered.

There's some discussion of this behaviour here as well https://hydro-sdk.io/docs/design-documents/ota

**Comment by chgibb** [comment]
@NoahHahm did the above help? Are you still seeing this issue?

**Comment by NoahHahm** [comment]
Thanks for the update. The simulator operation is perfect and there is no problem.

**Comment by chgibb** [comment]
Great to hear!

**Comment by NoahHahm** [comment]
debugging mode confirmed that it works normally.
I did command flutter run --release to upload the project to the actual device,
I tried running it in the actual ios device app, but found that it turned off immediately.

**Comment by NoahHahm** [comment]
Is there any way to run it without going through the registry service?

If you can read and execute the ota package from internal and external storage independently, it will be useful for production

**Comment by chgibb** [comment]
Running from storage is possible. `RunComponent` simply doesn't do so except to load `.ota` packages that have been cached after being downloaded from the configured registry. See the `OtaCacheMgr` class for example https://github.com/hydro-sdk/hydro-sdk/blob/master/lib/otaCacheMgr/otaCacheMgr.dart

In terms of the first run (without a registry), would running out of Flutter's asset bundle (https://flutter.dev/docs/development/ui/assets-and-images) make sense?

**Comment by NoahHahm** [comment]
First of all, I successfully completed the code push and used the RunComponent build, but the problem of turning off when running the release mode app still persists.

````
runApp(const RunComponent(
    project: "f2cfeb9f-d386-46c1-9c8d-00a8b797a129",
    component: "hotel-booking"));

noah@Noahui-iMac hotel-booking-app % npx hydroc codepush --private-key-file key.pem
All Hydro-SDK tools exist
Building project example-project
Building component hotel-booking
Lowering files
  [████████████████████████████████████████] 294/294 ota/index.ts
Assembling manifest...                 0.1s
Assembling package...                  0.7s
Publishing...                          2.4s
Successfully published example-project/hotel-booking
````

**Comment by chgibb** [comment]
The project name and component name passed to `RunComponent` should match what was published to the registry. If this is the test component you published (https://registry.hydro-sdk.io/#/component/45d0e4b7-5286-4001-b4f9-61975c3206c0), the project would be `noah` and component `hotel-booking`. That should also match in your project configuration (`hydro.json` by default).

**Comment by NoahHahm** [comment]
I think this is my mistake. thanks.
I've adjusted the code again as below, but the problem is still
`
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const RunComponent(project: "noah", component: "hotel-booking"));
}

{
    "project": "noah",
    "components": [
        {
            "name": "hotel-booking",
            "chunks": [
                {
                    "type": "mountable",
                    "baseUrl": "ota",
                    "entryPoint": "ota/index.ts"
                }
            ]
        }
    ]
}
`

**Comment by NoahHahm** [comment]
[hotel_booking_app.txt](https://github.com/hydro-sdk/hotel-booking-app/files/6918928/hotel_booking_app.txt)
https://user-images.githubusercontent.com/6405162/127907563-eacd8831-56a0-4a9e-b49d-f08daa9cd4e1.MP4

A simple log of the symptoms, but I don't know if it will help.
so I'll test it again tomorrow.
It might be my mistake.

**Comment by chgibb** [comment]
Does running `flutter run` (without the `--release` flag) work? What about on a simulator?

**Comment by NoahHahm** [comment]
I have successfully reinstalled flutter cleanly.
I think it was environmental twisted.
thanks for your help

**Comment by chgibb** [comment]
Good to hear it's working for you now @NoahHahm . Let me know if anything else comes up.
